### PR TITLE
fix: bloomPossibilities topics processing

### PR DESCRIPTION
**Pull request by kstdl**
Fix blooms generated by bloomPossibilities method. Because of this eth_getLogs rpc method was returning not all events as two elements in array was meaning AND, but not OR as it should be

### CODE REVIEW

**Comment by rattrap** [comment]
Works with multiple topics now:
```
{
  method: 'eth_getLogs',
  params: [
    {
      address: '0x00000000000000000000000000000000000000fe',
      topics: [
        [
          '0x12e144c27d0bad08abc77c66a640b5cf15a03a93f6582f40de6932b033a5fa5e',
          '0x4d10bd049775c77bd7f255195afba5088028ecb3c7c277d393ccff7934f2f92c',
          '0x7aa20e1f59764c9066578febd688a51375adbd654aff86cef56593a17a99071d',
          '0x9310ccfcb8de723f578a9e4282ea9f521f05ae40dc08f3068dfad528a65ee3c7',
          '0xc909daf778d180f43dac53b55d0de934d2f1e0b70412ca274982e4e6e894eb1a',
          '0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251',
          '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
          '0xf0ec9e0f6add850a1738c5822244e26ffc3d1f14da7537aa240582b25af12ad0',
          '0xf8bef3a6fe3b4c932b5b51c6472a89f171d039f4bacf18cff632208938bf0426',
          '0xfc25f8a919d19f2c2dfce21115718abc9ef2b1e0c9218a488f614c75be4184b7'
        ]
      ],
      fromBlock: '0x0',
      toBlock: 'latest'
    }
  ]
}
resp 0xc8
resp [
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x1a4aab8a265f81147d158ad9a44d372f43ab5d1ad7ba87b06717e77c7091172c',
    blockNumber: '0xe9',
    data: '0x',
    logIndex: '0x0',
    removed: false,
    topics: [
      '0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    transactionHash: '0xbca58ed390059a76b634e2c11cdc22509f9a437a3056361074b36336ec613218',
    transactionIndex: '0x6'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x1a4aab8a265f81147d158ad9a44d372f43ab5d1ad7ba87b06717e77c7091172c',
    blockNumber: '0xe9',
    data: '0x00000000000000000000000000000000000000000000003635c9adc5dea00000',
    logIndex: '0x1',
    removed: false,
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    transactionHash: '0xbca58ed390059a76b634e2c11cdc22509f9a437a3056361074b36336ec613218',
    transactionIndex: '0x6'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0xea1c8cc89766d55795187c0114d4e863b62f738ea57188b02f0db4c2928f9779',
    blockNumber: '0x145',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    logIndex: '0x0',
    removed: false,
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    transactionHash: '0xc99b32510d6f90b69d9109550763e530e99b2173a1c8f7f6c75b5ed4a30f5a61',
    transactionIndex: '0x0'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x7b42e46b2f383bf97993fe676a0987c9669b7180e3d080ae606cb20038be4851',
    blockNumber: '0x15d',
    data: '0x',
    logIndex: '0x0',
    removed: false,
    topics: [
      '0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    transactionHash: '0xff179e992f6b4a4f86988564d2e990fe5abcf3ca09ba3fd56bbd34ad80f86dda',
    transactionIndex: '0x0'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x7b42e46b2f383bf97993fe676a0987c9669b7180e3d080ae606cb20038be4851',
    blockNumber: '0x15d',
    data: '0x00000000000000000000000000000000000000000000003635c9adc5dea00000',
    logIndex: '0x1',
    removed: false,
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    transactionHash: '0xff179e992f6b4a4f86988564d2e990fe5abcf3ca09ba3fd56bbd34ad80f86dda',
    transactionIndex: '0x0'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x514caf37f6d98ef0a9d7dd9b2e9f67b3c6ba938ff977cc7a21f11b3e01a33e3c',
    blockNumber: '0x175',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    logIndex: '0x0',
    removed: false,
    topics: [
      '0x12e144c27d0bad08abc77c66a640b5cf15a03a93f6582f40de6932b033a5fa5e',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    transactionHash: '0x3623cc8da8090887d3439c0c6bf4c141bd9c4bea1dbb894f4a643e7d2f7ee110',
    transactionIndex: '0x0'
  },
  {
    address: '0x00000000000000000000000000000000000000fe',
    blockHash: '0x77b8d39bb8479c1f1945f94e6a165ff69f1da49d25b2132fbb1f1cf1a4cf28f0',
    blockNumber: '0x180',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    logIndex: '0x0',
    removed: false,
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    transactionHash: '0xc3987e666d4a8028ecf4f93ff8826ba7ae751fcb00bbbe3a74c75b0f9df7e1a9',
    transactionIndex: '0x0'
  }
]
[
  Log {
    provider: Provider {},
    transactionHash: '0xbca58ed390059a76b634e2c11cdc22509f9a437a3056361074b36336ec613218',
    blockHash: '0x1a4aab8a265f81147d158ad9a44d372f43ab5d1ad7ba87b06717e77c7091172c',
    blockNumber: 233,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x',
    topics: [
      '0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    index: 0,
    transactionIndex: 6
  },
  Log {
    provider: Provider {},
    transactionHash: '0xbca58ed390059a76b634e2c11cdc22509f9a437a3056361074b36336ec613218',
    blockHash: '0x1a4aab8a265f81147d158ad9a44d372f43ab5d1ad7ba87b06717e77c7091172c',
    blockNumber: 233,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x00000000000000000000000000000000000000000000003635c9adc5dea00000',
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    index: 1,
    transactionIndex: 6
  },
  Log {
    provider: Provider {},
    transactionHash: '0xc99b32510d6f90b69d9109550763e530e99b2173a1c8f7f6c75b5ed4a30f5a61',
    blockHash: '0xea1c8cc89766d55795187c0114d4e863b62f738ea57188b02f0db4c2928f9779',
    blockNumber: 325,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    index: 0,
    transactionIndex: 0
  },
  Log {
    provider: Provider {},
    transactionHash: '0xff179e992f6b4a4f86988564d2e990fe5abcf3ca09ba3fd56bbd34ad80f86dda',
    blockHash: '0x7b42e46b2f383bf97993fe676a0987c9669b7180e3d080ae606cb20038be4851',
    blockNumber: 349,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x',
    topics: [
      '0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    index: 0,
    transactionIndex: 0
  },
  Log {
    provider: Provider {},
    transactionHash: '0xff179e992f6b4a4f86988564d2e990fe5abcf3ca09ba3fd56bbd34ad80f86dda',
    blockHash: '0x7b42e46b2f383bf97993fe676a0987c9669b7180e3d080ae606cb20038be4851',
    blockNumber: 349,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x00000000000000000000000000000000000000000000003635c9adc5dea00000',
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    index: 1,
    transactionIndex: 0
  },
  Log {
    provider: Provider {},
    transactionHash: '0x3623cc8da8090887d3439c0c6bf4c141bd9c4bea1dbb894f4a643e7d2f7ee110',
    blockHash: '0x514caf37f6d98ef0a9d7dd9b2e9f67b3c6ba938ff977cc7a21f11b3e01a33e3c',
    blockNumber: 373,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    topics: [
      '0x12e144c27d0bad08abc77c66a640b5cf15a03a93f6582f40de6932b033a5fa5e',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca',
      '0x0000000000000000000000002012c958e6f1f933006c86e12c8e4d16399598eb'
    ],
    index: 0,
    transactionIndex: 0
  },
  Log {
    provider: Provider {},
    transactionHash: '0xc3987e666d4a8028ecf4f93ff8826ba7ae751fcb00bbbe3a74c75b0f9df7e1a9',
    blockHash: '0x77b8d39bb8479c1f1945f94e6a165ff69f1da49d25b2132fbb1f1cf1a4cf28f0',
    blockNumber: 384,
    removed: false,
    address: '0x00000000000000000000000000000000000000fe',
    data: '0x00000000000000000000000000000000000000000008455ee04a53826b600000',
    topics: [
      '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
      '0x0000000000000000000000002cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9',
      '0x000000000000000000000000c6e88ed657422550e24b0f40e757f7cb8f63f6ca'
    ],
    index: 0,
    transactionIndex: 0
  }
]
```

**Comment by rattrap** [comment]
Another issue I found is, if I give it more than 4 "AND" topics, it will crash the node:
Request:
```
{
  method: 'eth_getLogs',
  params: [
    {
      address: '0x00000000000000000000000000000000000000fe',
      topics: [
        '0xf0ec9e0f6add850a1738c5822244e26ffc3d1f14da7537aa240582b25af12ad0',
        '0xc909daf778d180f43dac53b55d0de934d2f1e0b70412ca274982e4e6e894eb1a',
        '0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b',
        '0x12e144c27d0bad08abc77c66a640b5cf15a03a93f6582f40de6932b033a5fa5e',
        '0x9310ccfcb8de723f578a9e4282ea9f521f05ae40dc08f3068dfad528a65ee3c7'
      ],
      fromBlock: '0x0',
      toBlock: 'latest'
    }
  ]
}
```

Logs:
```
pr-2482-taraxa-node-2 taraxa-node 0x00007fe6477fe640 HTTP [2023-05-19 09:40:46.293702] DEBUG: Received: POST / HTTP/1.1
pr-2482-taraxa-node-2 taraxa-node Host: rpc-pr-2482.prnet.taraxa.io
pr-2482-taraxa-node-2 taraxa-node X-Request-ID: 9e5e8edf19ce441e10865c112402d520
pr-2482-taraxa-node-2 taraxa-node X-Real-IP: 86.120.16.208
pr-2482-taraxa-node-2 taraxa-node X-Forwarded-For: 86.120.16.208
pr-2482-taraxa-node-2 taraxa-node X-Forwarded-Host: rpc-pr-2482.prnet.taraxa.io
pr-2482-taraxa-node-2 taraxa-node X-Forwarded-Port: 443
pr-2482-taraxa-node-2 taraxa-node X-Forwarded-Proto: https
pr-2482-taraxa-node-2 taraxa-node X-Scheme: https
pr-2482-taraxa-node-2 taraxa-node Content-Length: 915
pr-2482-taraxa-node-2 taraxa-node content-type: application/json
pr-2482-taraxa-node-2 taraxa-node accept-encoding: gzip
pr-2482-taraxa-node-2 taraxa-node
pr-2482-taraxa-node-2 taraxa-node [{"method":"eth_chainId","params":[],"id":3,"jsonrpc":"2.0"},{"method":"eth_getLogs","params":[{"address":"0x00000000000000000000000000000000000000fe","topics":["0xf0ec9e0f6add850a1738c5822244e26ffc3d1f14da7537aa240582b25af12ad0","0xc909daf778d180f43dac53b55d0de934d2f1e0b70412ca274982e4e6e894eb1a","0xe5541a6b6103d4fa7e021ed54fad39c66f27a76bd13d374cf6240ae6bd0bb72b","0x12e144c27d0bad08abc77c66a640b5cf15a03a93f6582f40de6932b033a5fa5e","0x9310ccfcb8de723f578a9e4282ea9f521f05ae40dc08f3068dfad528a65ee3c7","0xfc25f8a919d19f2c2dfce21115718abc9ef2b1e0c9218a488f614c75be4184b7","0xf8bef3a6fe3b4c932b5b51c6472a89f171d039f4bacf18cff632208938bf0426","0x4d10bd049775c77bd7f255195afba5088028ecb3c7c277d393ccff7934f2f92c","0x7aa20e1f59764c9066578febd688a51375adbd654aff86cef56593a17a99071d","0xd09501348473474a20c772c79c653e1fd7e8b437e418fe235d277d2c88853251"],"fromBlock":"0x0","toBlock":"latest"}],"id":4,"jsonrpc":"2.0"}]
pr-2482-taraxa-node-2 taraxa-indexer ERRO[2023-05-19T09:40:46] Error occurred. Restart indexing              error="websocket: close 1006 (abnormal closure): unexpected EOF" period=389
pr-2482-taraxa-node-2 taraxa-node /entrypoint.sh: line 31:     7 Segmentation fault      (core dumped) taraxad $FLAGS "${@:2}"
pr-2482-taraxa-node-2 taraxa-node Copying dump (if any) to /root/.taraxa
pr-2482-taraxa-node-2 taraxa-node '/core.taraxad.7.1684489246' -> '/root/.taraxa/core.taraxad.7.1684489246'
pr-2482-taraxa-node-2 taraxa-node Sleeping forever for diagnosis
pr-2482-taraxa-node-2 taraxa-node Crashed. Waiting on diagnosis...
```

**Comment by rattrap** [comment]
Core dump: https://drive.google.com/file/d/1TKQTkD4IHw92z5zPOalWcq-QOR2gRrxV/view?usp=sharing

**Review by mfrankovi — APPROVED** [review]

**Pull request merged**
