### PR TITLE
Set pbft step

### PR DESCRIPTION
**Pull request by mfrankovi**
Override pbft step by cmd line option

### CODE REVIEW

**Review by JakubFornadel — APPROVED** [review]

**Comment by gaoqi8649** [comment]
I think this is not help for our nodes running on cloud, because this need a reboot and setting step value on command line.
There is setPbftStep in PBFT manager, I am not sure if we could create a RPC call for that.

**Comment by JakubFornadel** [comment]
@mfrankovi can we close this PR ?

**Comment by mfrankovi** [comment]
> @mfrankovi can we close this PR ?

@justinsnapp do we still want to have this?

**Comment by gaoqi8649** [comment]
I think for testing purpose, that's better in RPC call instead of CLI

**Comment by mfrankovi** [comment]
I am closing this. Lets keep the branch alive a bit more if we ever decide to use it

**Pull request closed without merging**
