### PR TITLE
chore(unit test): Fix pbft manager unit tests timing issue

### PR DESCRIPTION
**Pull request by gaoqi8649**
Cannot reproduce at local, try fixing running time and waiting time

### CODE REVIEW

**Comment by JakubFornadel** [comment]
so what are you fixing if you cannot reproduce it ?

**Comment by JakubFornadel** [comment]
@justinsnapp please dont use "update-branch" button, which merges develop into the branch... We agreed we are going to use rebase for this purpose so the history(graph) is nice and clean... Currently there is no way of disabling the button button(or change its policy to rebase) and keeping the notification "your branch is not up to date". I left it enabled  so people can see their branch is not up to date, but they should manually rebase their branch instead of pushing 'update-branch' button

+ I would really like to start enforcing 2 reviews (approvals) before merging into develop. So instead of merging PR's that dont have approvals as we do now we could write to people "hey this is my PR, which is finished please either approve it or comment if you see some problems"... It might take few days/weeks for people to get used to it but it will force us to do proper reviews and that is for sure beneficial :)

**Comment by justinsnapp** [comment]
@JakubFornadel yeah I agree.  I have been being bad for sure.

**Comment by gaoqi8649** [comment]
> so what are you fixing if you cannot reproduce it ?
The unit tests could pass on Linux machine, but will fail on Mac machine on circleci. I checked the fail logs on circleci, find this is unit test waiting time issue.

**Comment by JakubFornadel** [comment]
> > so what are you fixing if you cannot reproduce it ?
> > The unit tests could pass on Linux machine, but will fail on Mac machine on circleci. I checked the fail logs on circleci, find this is unit test waiting time issue.

hmm are you sure about 120s instead of 60s or its just raw guess ? WOuld be cool if keep this waiting time reasonably small as our tests already take a lot of time... We might optimize them 1 day when there is time for that...

**Comment by gaoqi8649** [comment]
> > > so what are you fixing if you cannot reproduce it ?
> > > The unit tests could pass on Linux machine, but will fail on Mac machine on circleci. I checked the fail logs on circleci, find this is unit test waiting time issue.
> 
> hmm are you sure about 120s instead of 60s or its just raw guess ? WOuld be cool if keep this waiting time reasonably small as our tests already take a lot of time... We might optimize them 1 day when there is time for that...

From the CircleCI Mac machine running logs, knows 60s is not enough. So I just double the time. In the unit test,  will check every 1s. So it will exist if finish early. The timeout changes to 120s

**Review by MatusKysel — APPROVED** [review]

**Review by justinsnapp — APPROVED** [review]

**Pull request merged**
