### PR TITLE
Feature/issue 1883

### PR DESCRIPTION
**Pull request by rjonczy**
## Purpose

We want to use current helm chart to deplot prnet.

## How does the solution address the problem

Change of circleci process in order to deploy current helm chart.

## Changes made

Changed circle ci pipeline

### CODE REVIEW

**Review by MatusKysel — APPROVED** [review]

**Review by rattrap — CHANGES_REQUESTED** [review]
I will have another look after you un-comment the smoketests

**Comment by rjonczy** [comment]
> I will have another look after you un-comment the smoketests

damn it. forgot about it. I was testing many times and didnt want to wait so long. fixing

**Comment by rjonczy** [comment]
@rattrap brought the tests back.

**Review by rattrap — APPROVED** [review]
LGTM

**Pull request merged**
