### PR TITLE
Fix: do not start build-docker-image when using prnet commands

### PR DESCRIPTION
**Pull request by rjonczy**
## Purpose

`build-docker-image` was triggered when using command for prnets:
- \deploy
- \cleanup
- \redeploy

## How does the solution address the problem

Added conditions to job.

## Changes made

Added conditions to job.

### CODE REVIEW

**Review by JakubFornadel — APPROVED** [review]

**Review by rattrap — APPROVED** [review]
Perfect. This should save us some $$$
LGTM

**Review by rattrap — COMMENTED** [review]
LGTM

**Pull request merged**
