### PR TITLE
Non finalized transactions fix

### PR DESCRIPTION
**Pull request by mfrankovi**
Fix for non finalized transactions memory leak

### CODE REVIEW

**Review by MatusKysel — APPROVED** [review]

**Review by JakubFornadel — COMMENTED** [review]
So why dont we rather merge develop (which already has it) into the testnet ?

**Comment by justinsnapp** [comment]
> So why dont we rather merge develop (which already has it) into the testnet ?

Is that only change on develop?

**Comment by JakubFornadel** [comment]
> > So why dont we rather merge develop (which already has it) into the testnet ?
> 
> Is that only change on develop?

I think so, will double check

**Comment by justinsnapp** [comment]
> > > So why dont we rather merge develop (which already has it) into the testnet ?
> > 
> > 
> > Is that only change on develop?
> 
> I think so, will double check
> 
> Checked and yes this is the only change

ok then @JakubFornadel  if you want to close this and merge develop to testnet, please do.  :-)

**Comment by justinsnapp** [comment]
Merged develop to testnet, and this change already included in similar PR to develop today.  Thanks @mfrankovi !

**Pull request closed without merging**
