### PR TITLE
chore(final_chain): move block to final chain instead reading from DB

### PR DESCRIPTION
**Pull request by MatusKysel**

### CODE REVIEW

**Review by gaoqi8649 — APPROVED** [review]

**Comment by JakubFornadel** [comment]
All the functionality from this PR is implemented in my rewards PR so if we merge this, it is going to be just 1 huge conflict for me :/

**Comment by MatusKysel** [comment]
> All the functionality from this PR is implemented in my rewards PR so if we merge this, it is going to be just 1 huge conflict for me :/

so why did not you create this PR before? it is not good practice to combine all changes in one huge PR if it is possible to split it

**Comment by JakubFornadel** [comment]
> > All the functionality from this PR is implemented in my rewards PR so if we merge this, it is going to be just 1 huge conflict for me :/
> 
> so why did not you create this PR before? it is not good practice to combine all changes in one huge PR if it is possible to split it

well my mistake then. To be honest I have been working on it for such a long time now and faced so many frustrating problems that I simply did not separate it  as it was developed incrementally all together so I would have to create new branch and copy paste there only some part of the new code, which was like naah... 

I will gladly let you do the next huge task(even all of them) so you can split it into the 10 separate PR's and do it the right way :)

**Review by JakubFornadel — APPROVED** [review]

**Comment by kstdl** [comment]
Maybe for develop we should wait for @JakubFornadel PR to be merged to not spend time on merging? If we want it for some reason on testnet than we can merge it to testnet directly

**Pull request merged**
